-- Data Harmonisasi Baru 2026 (Total 36 Data)
-- Generated from ##Data Hasil Rapat Harmonisasi 2026.xlsx on 2026-08-13 08:59:21
-- TANPA TRUNCATE / DELETE

INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Toraja Utara tentang Pendelegasian Kewenangan Penyelenggaraan Pelayanan Perizinan Berusaha, Perizinan dan Nonperizinan kepada Kepala Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'Kabupaten Toraja Utara', '2026-07-30', '2026-08-04', 'Abdillah', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Toraja Utara tentang Penanaman Modal', 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'Kabupaten Toraja Utara', '2026-07-31', '2026-08-04', 'Mayasari', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Pinrang tentang Pelaksanaan Peraturan Daerah Kabupaten Pinrang Nomor 7 Tahun 2021 tentang Tanggung Jawab Sosial dan Lingkungan Badan Usaha', 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'Kabupaten Pinrang', '2026-07-30', '2026-08-04', 'Arpan', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Pinrang tentang Perubahan atas Peraturan Bupati Pinrang Nomor 73 Tahun 2021 tentang Pendelegasian Kewenangan Pelayanan Perizinan Berusaha dan Perizinan Nonberusaha kepada Kepala Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu Kabupaten Pinrang', 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'Kabupaten Pinrang', '2026-07-30', '2026-08-04', 'Syafar', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Provinsi Sulawesi Selatan tentang Penyelenggaraan Perlindungan Pekerja Migran', 'Dinas Ketenagakerjaan', 'Provinsi Sulawesi Selatan', '2026-07-28', '2026-08-04', 'Syarif', 'Dikembalikan', 'Dikembalikan karena rapat harmonisasi tidak dihadiri oleh pejabat Eselon II dari instansi pemrakarsa', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Enrekang tentang Standar Pelayanan pada Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu Kabupaten Enrekang', 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'Kabupaten Enrekang', '2026-07-29', '2026-08-05', 'Zulkifli', 'Dikembalikan', 'Standar Pelayanan seharusnya tidak diatur dengan Peraturan Bupati tetapi cukup ditetapkan dengan Keputusan Bupati sesuai dengan Pasal 13 Permendagri Nomor 138 Tahun 2017 tentang Penyelenggaraan Pelayanan Terpadu Satu Pintu Daerah', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Wajo tentang Perusahaan Perseroan Daerah Wajo Energi Jaya', 'Bagian Perekonomian Sekretariat Daerah', 'Kabupaten Wajo', '2026-07-31', '2026-08-05', 'Irma Wahyuni', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Petunjuk Teknis Standar Operasional Prosedur Satuan Polisi Pamong Praja', 'Satpol PP', 'Kabupaten Wajo', '2026-07-31', '2026-08-05', 'Fachruddin', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Pedoman Pengelolaan Pasar Rakyat', 'Dinas Perindustrian, Perdagangan, Koperasi Usaha Kecil dan Menengah', 'Kabupaten Wajo', '2026-08-03', '2026-08-05', 'Pramita', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Tana Toraja tentang Penyelenggaraan Ketertiban Umum dan Ketenteraman Masyarakat serta Pelindungan Masyarakat', 'Satpol PP', 'Kabupaten Tana Toraja', '2026-07-30', '2026-08-06', 'Baharuddin', 'Dikembalikan', 'Substansi masih perlu disempurnakan', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Tana Toraja tentang Pengelolaan Air Limbah Domestik', 'Dinas Pekerjaan Umum dan Tata Ruang', 'Kabupaten Tana Toraja', '2026-07-31', '2026-08-06', 'Abdillah', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Tana Toraja tentang Penanggulangan Tuberkulosis', 'Dinas Kesehatan', 'Kabupaten Tana Toraja', '2026-07-31', '2026-08-06', 'Danu', 'Dikembalikan', 'pengaturan pada Rancangan Peraturan Kepala Daerah tentang  Penanggulangan Tuberkulosis ini terlalu luas, harus lebih fokus pada penaggulangan sesuai pada Peraturan Menteri Kesehatan Nomor 67 Tahun 2016 tentang Penanggulangan Tuberkulosis dan harus mengatur tentang pembentukan desa siaga tuberkulosis sesuai pada Peraturan Presiden Nomor 67 Tahun 2021', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Tana Toraja tentang Peta Jalan Pembangunan Kependudukan Kabupaten Tana Toraja Tahun 2025–2029', 'Dinas Pemberdayaan Perempuan, Perlindungan Anak, Pengendalian Penduduk, dan Keluarga Berencana', 'Kabupaten Tana Toraja', '2026-07-31', '2026-08-06', 'Kurniati', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Tana Toraja tentang Tarif Layanan pada Badan Layanan Umum Daerah Rumah Sakit Umum Daerah Lakipadada', 'RSUD Lakipadada', 'Kabupaten Tana Toraja', '2026-07-31', '2026-08-06', 'Fadli', 'Dikembalikan', 'Prosedur pengusulan tarif layanan baru BLUD RS Lakipadada masih perlu dilengkapi sesuai dengan ketentuan Pasal 83 Peraturan Menteri Dalam Negeri Nomor 79 Tahun 2018 tentang Badan Layanan Umum Daerah, dan teknik penyusunan Rancangan Peraturan Bupati tersebut masih perlu disempurnakan', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Luwu tentang Pola Tata Kelola Badan Layanan Umum Daerah Unit Pelaksana Teknis Pusat Kesehatan Masyarakat', 'Dinas Kesehatan', 'Kabupaten Luwu', '2026-08-02', '2026-08-06', 'Fatmawati', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Luwu tentang Rencana Strategis Badan Layanan Umum Daerah Unit Pelaksana Teknis Pusat Kesehatan Masyarakat Tahun 2026–2029', 'Dinas Kesehatan', 'Kabupaten Luwu', '2026-08-02', '2026-08-06', 'Nuryuli', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Luwu tentang Standar Pelayanan Minimal Badan Layanan Umum Daerah Unit Pelaksana Teknis Pusat Kesehatan Masyarakat', 'Dinas Kesehatan', 'Kabupaten Luwu', '2026-08-02', '2026-08-06', 'Rismayana', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Luwu tentang Pengelolaan Keuangan Badan Layanan Umum Daerah Unit Pelaksana Teknis Pusat Kesehatan Masyarakat', 'Dinas Kesehatan', 'Kabupaten Luwu', '2026-08-02', '2026-08-06', 'Norma', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Luwu tentang Tata Cara Kerja Sama dengan Pihak Lain Badan Layanan Umum Daerah Unit Pelaksana Teknis Pusat Kesehatan Masyarakat', 'Dinas Kesehatan', 'Kabupaten Luwu', '2026-08-02', '2026-08-06', 'Asryani', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Provinsi Sulawesi Selatan tentang Penghitungan, Pelaporan, dan Pembayaran kepada Pemerintah Daerah atas Penerimaan Daerah yang Diperoleh dari Keuntungan Bersih Pemegang Izin Usaha Pertambangan Khusus', 'Badan Pendapatan Daerah', 'Provinsi Sulawesi Selatan', '2026-08-03', '2026-08-06', 'Mayasari', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Provinsi Sulawesi Selatan tentang Perubahan Bentuk Hukum Perseroan Terbatas Perusahaan Penjaminan Kredit Daerah Sulawesi Selatan Menjadi Perusahaan Perseroan Daerah Penjaminan Kredit Daerah Sulawesi Selatan', 'Biro Perekonomian dan Adminsitrasi Pembangunan Sekretariat Daerah', 'Provinsi Sulawesi Selatan', '2026-08-03', '2026-08-06', 'Abdillah', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kota Makassar tentang Penataan Kader Institusi Masyarakat Perkotaan Bangga Kencana dan Sub Institusi Masyarakat Perkotaan Bangga Kencana', 'Dinas Pengendalian Penduduk dan Keluarga Berencana', 'Kota Makassar', '2026-08-03', '2026-08-06', 'Firmanullah', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Kedudukan, Susunan Organisasi, Tugas dan Fungsi, serta Tata Kerja Dinas Pemuda, Olahraga, Pariwisata dan Ekonomi Kreatif', 'Dinas Pemuda, Olahraga, Pariwisata dan Ekonomi Kreatif', 'Kabupaten Wajo', '2026-08-06', '2026-08-10', 'Irma Wahyuni', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Kedudukan, Susunan Organisasi, Tugas dan Fungsi, serta Tata Kerja Badan Pendapatan Daerah', 'Badan Pendapatan Daerah', 'Kabupaten Wajo', '2026-08-06', '2026-08-10', 'Syarif', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Kedudukan, Susunan Organisasi, Tugas dan Fungsi, serta Tata Kerja Satuan Polisi Pamong Praja', 'Satuan Polisi Pamong Praja', 'Kabupaten Wajo', '2026-08-06', '2026-08-10', 'Fachruddin', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Kedudukan, Susunan Organisasi, Tugas dan Fungsi, serta Tata Kerja Badan Penanggulangan Bencana Daerah', 'Badan Penanggulangan Bencana Daerah', 'Kabupaten Wajo', '2026-08-06', '2026-08-10', 'Yuyun', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Kedudukan, Susunan Organisasi, Tugas dan Fungsi, serta Tata Kerja Dinas Pemadam Kebakaran dan Penyelamatan', 'Dinas Pemadam Kebakaran dan Penyelamatan', 'Kabupaten Wajo', '2026-08-06', '2026-08-10', 'Pramita', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Kedudukan, Susunan Organisasi, Tugas dan Fungsi serta Tata Kerja Dinas Pekerjaan Umum dan Tata Ruang Kabupaten Wajo', 'Dinas Pekerjaan Umum dan Tata Ruang Kabupaten Wajo', 'Kabupaten Wajo', '2026-08-06', '2026-08-10', 'Fatmawati', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Kedudukan, Susunan Organisasi, Tugas dan Fungsi, serta Tata Kerja Dinas Sosial', 'Dinas Sosial', 'Kabupaten Wajo', '2026-08-06', '2026-08-10', 'Nuryuli', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Kedudukan, Susunan Organisasi, Tugas dan Fungsi, serta Tata Kerja Dinas Pengendalian Penduduk, Keluarga Berencana, Pemberdayaan Perempuan dan Perlindungan Anak', 'Dinas Pengendalian Penduduk, Keluarga Berencana, Pemberdayaan Perempuan dan Perlindungan Anak', 'Kabupaten Wajo', '2026-08-06', '2026-08-10', 'Zulkifli', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Kedudukan, Susunan Organisasi, Tugas dan Fungsi serta Tata Kerja Dinas Perumahan, Kawasan Permukiman dan Pertanahan', 'Dinas Perumahan, Kawasan Permukiman dan Pertanahan', 'Kabupaten Wajo', '2026-08-06', '2026-08-10', 'Wahyu', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Kedudukan, Susunan Organisasi, Tugas dan Fungsi, serta Tata Kerja Badan Keuangan dan Aset Daerah', 'Badan Keuangan dan Aset Daerah', 'Kabupaten Wajo', '2026-08-06', '2026-08-10', 'Rismayana', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Jeneponto tentang Pedoman Pengelolaan Keuangan Badan Layanan Umum Daerah', 'RSUD Lanto Dg Pasewang', 'Kabupaten Jeneponto', '2026-08-06', '2026-08-11', 'Asryani', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Luwu Utara tentang Perubahan Ketiga atas Peraturan Bupati Luwu Utara Nomor 2 Tahun 2021 tentang Tata Cara Penyelenggaraan Pemilihan Kepala Desa', 'Dinas Pemberdayaan Masyarakat dan Desa', 'Kabupaten Luwu Utara', '2026-08-07', '2026-08-13', 'Mayasari', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Luwu Utara tentang Penanggulangan Tuberkulosis', 'Dinas Kesehatan', 'Kabupaten Luwu Utara', '2026-08-07', '2026-08-13', 'Rugaya', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Luwu Utara tentang Rencana Aksi Daerah Penanggulangan Tuberkulosis Tahun 2026–2030', 'Dinas Kesehatan', 'Kabupaten Luwu Utara', '2026-08-07', '2026-08-13', 'Agry', 'Diterima', '', NULL);
