-- Data Harmonisasi 2026 (Generated from sheet 'Data Harmonisasi')
-- File: ##Data Hasil Rapat Harmonisasi 2026.xlsx
-- Generated on: 2026-09-10 05:52:38

INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Sidenreng Rappang tentang Penanggulangan Tuberkulosis', 'Dinas Kesehatan', 'Kabupaten Sidenreng Rappang', '2026-08-26', '2026-08-31', 'Rismayana', 'Dikembalikan', 'Agar muatan Rancangan Peraturan Bupati tersebut disesuaikan dengan Peraturan Menteri Kesehatan Nomor 3 Tahun 2026 tentang Penanggulangan Penyakit dan menambahkan materi muatan lokal yang berkaitan dengan penanggulangan tuberkulosis', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Pinrang tentang Petunjuk Teknis Penyusunan Rencana Pembangunan Jangka Menengah Desa dan Rencana Kerja Pemerintah Desa serta Petunjuk Teknis Pelaksanaan Kegiatan Pembangunan Desa', 'Dinas Pemberdayaan Masyarakat dan Desa', 'Kabupaten Pinrang', '2026-08-26', '2026-09-01', 'Firmanullah', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Pinrang tentang Penerapan Transaksi Non Tunai dalam Pengelolaan Keuangan Desa', 'Dinas Pemberdayaan Masyarakat dan Desa', 'Kabupaten Pinrang', '2026-08-26', '2026-09-01', 'Fadli', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Pinrang tentang Pedoman Penyusunan Anggaran Pendapatan dan Belanja Desa Tahun Anggaran 2026', 'Dinas Pemberdayaan Masyarakat dan Desa', 'Kabupaten Pinrang', '2026-08-26', '2026-09-01', 'Fira', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Pinrang tentang Tata Cara Pengawasan Objek Pajak Daerah', 'Badan Pendapatan Daerah', 'Kabupaten Pinrang', '2026-08-28', '2026-09-01', 'Danu', 'Dikembalikan', 'Seharusnya masuk dalam Peraturan Kepala Daerah tentang Ketentuan Umum dan Tata Cara Pemungutan Pajak dan Retribusi', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Soppeng tentang Tata Cara Penyelenggaraan Cadangan Pangan Pemerintah Daerah', 'DPRD', 'Kabupaten Soppeng', '2026-08-28', '2026-09-01', 'Pramita', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Barru tentang Perubahan Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2026', 'Badan Keuangan dan Aset Daerah', 'Kabupaten Barru', '2026-08-27', '2026-09-02', 'Nurlindah', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Barru tentang Penjabaran Perubahan Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2026', 'Badan Keuangan dan Aset Daerah', 'Kabupaten Barru', '2026-08-27', '2026-09-02', 'Nurul', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Barru tentang Rencana Aksi Daerah Penerapan Standar Pelayanan Minimal Tahun 2025–2030', 'Bagian Pemerintahan Sekretariat Daerah', 'Kabupaten Barru', '2026-08-27', '2026-09-02', 'Rugaya', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Barru tentang Perubahan atas Peraturan Bupati Barru Nomor 96 Tahun 2025 tentang Beasiswa bagi Mahasiswa', 'Dinas Pariwisata, Ekonomi Kreatif, Kepemudaan dan Olahraga', 'Kabupaten Barru', '2026-08-27', '2026-09-02', 'Mayasari', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Soppeng tentang Pemotongan Hewan', 'Dinas Peternakan, Kesehatan Hewan dan Perikanan', 'Kabupaten Soppeng', '2026-08-27', '2026-09-02', 'Baharuddin', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Soppeng tentang Perubahan Kedua atas Peraturan Daerah Kabupaten Soppeng Nomor 5 Tahun 2016 tentang Pembentukan dan Susunan Perangkat Daerah', 'Bagian Organisasi Sekretariat Daerah', 'Kabupaten Soppeng', '2026-08-27', '2026-09-02', 'Syafar', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Kepulauan Selayar tentang Pembentukan, Kedudukan, Susunan Organisasi, Tugas dan Fungsi serta Tata Kerja Unit Pelaksana Teknis Daerah Sistem Pengelolaan Air Limbah Domestik pada Dinas Pekerjaan Umum dan Tata Ruang', '-', 'Kabupaten Kepulauan Selayar', '2026-08-24', '2026-09-03', 'Nuryuli', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Kepulauan Selayar tentang Perubahan atas Peraturan Bupati Kepulauan Selayar Nomor 26 Tahun 2024 tentang Kedudukan, Susunan Organisasi, Tugas dan Fungsi serta Tata Kerja Dinas Pekerjaan Umum dan Tata Ruang', '-', 'Kabupaten Kepulauan Selayar', '2026-08-24', '2026-09-03', 'Wahyu', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Sinjai tentang Pelaksanaan Perizinan, Pembinaan dan Pengawasan Produksi Pangan Olahan', 'DPRD', 'Kabupaten Sinjai', '2026-08-26', '2026-09-03', 'Syarif', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Sidenreng Rappang tentang Perubahan Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2026', 'Badan Keuangan dan Aset Daerah', 'Kabupaten Sidenreng Rappang', '2026-09-01', '2026-09-03', 'Adryana', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Sidenreng Rappang tentang Penjabaran Perubahan Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2026', 'Badan Keuangan dan Aset Daerah', 'Kabupaten Sidenreng Rappang', '2026-09-01', '2026-09-03', 'Norma', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Pangkajene dan Kepulauan tentang Perubahan Kedua atas Peraturan Bupati Nomor 22 Tahun 2024 tentang Pemberian Bantuan Biaya Pendidikan bagi Mahasiswa Keluarga Tidak Mampu dan Mahasiswa Berprestasi', '-', 'Kabupaten Pangkajene dan Kepulauan', '2026-09-01', '2026-09-07', 'Firmanullah', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Pangkajene dan Kepulauan tentang Standar Pelayanan Minimal pada Badan Layanan Umum Daerah Unit Pelaksana Teknis Daerah Pusat Kesehatan Masyarakat', '-', 'Kabupaten Pangkajene dan Kepulauan', '2026-09-01', '2026-09-07', 'Kurniati', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Pangkajene dan Kepulauan tentang Sistem Remunerasi pada Badan Layanan Umum Daerah Unit Pelaksana Teknis Daerah Pusat Kesehatan Masyarakat', '-', 'Kabupaten Pangkajene dan Kepulauan', '2026-09-01', '2026-09-07', 'Baharuddin', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Pangkajene dan Kepulauan tentang Tata Kelola Badan Layanan Umum Daerah pada Rumah Sakit Umum Daerah Batara Siang', '-', 'Kabupaten Pangkajene dan Kepulauan', '2026-09-01', '2026-09-07', 'Fadli', 'Dikembalikan', 'Masih perlu dilakukan penyempurnaan substansi sesuai dengan Peraturan Menteri Dalam Negeri Nomor 79 Tahun 2018 tentang Badan Layanan Umum Daerah dan perbaikan teknik penyusunan peraturan perundang-undangan sesuai dengan Undang-Undang Nomor 12 Tahun 2011 tentang Pembentukan Peraturan Perundang-undangan.', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Jeneponto tentang Perubahan atas Peraturan Bupati Jeneponto Nomor 25 Tahun 2021 tentang Organisasi dan Tata Kerja Unit Pelaksana Teknis Satuan Pendidikan Sekolah Dasar Negeri dan Sekolah Menengah Pertama Negeri pada Dinas Pendidikan dan Kebudayaan', '-', 'Kabupaten Jeneponto', '2026-09-01', '2026-09-08', 'Asryani', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Jeneponto tentang Kedudukan, Susunan Organisasi, Tugas dan Fungsi serta Tata Kerja Dinas Kesehatan', '-', 'Kabupaten Jeneponto', '2026-09-01', '2026-09-08', 'Dio Batari', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Jeneponto tentang Pembentukan, Kedudukan, Susunan Organisasi, Tugas dan Fungsi serta Tata Kerja Unit Pelaksana Teknis Daerah Pusat Kesehatan Masyarakat pada Dinas Kesehatan', '-', 'Kabupaten Jeneponto', '2026-09-01', '2026-09-08', 'Syafar', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Toraja Utara tentang Perubahan Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2026', '-', 'Kabupaten Toraja Utara', '2026-09-03', '2026-09-08', 'Mayasari', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Toraja Utara tentang Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2027', '-', 'Kabupaten Toraja Utara', '2026-09-03', '2026-09-08', 'Mayasari', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Toraja Utara tentang Penjabaran Perubahan Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2026', '-', 'Kabupaten Toraja Utara', '2026-09-03', '2026-09-08', 'Nurlindah', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Toraja Utara tentang Penjabaran Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2027', '-', 'Kabupaten Toraja Utara', '2026-09-03', '2026-09-08', 'Nurlindah', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Toraja Utara tentang Perubahan atas Peraturan Bupati Nomor 59 Tahun 2024 tentang Ketentuan Umum dan Tata Cara Pemungutan Pajak Daerah', '-', 'Kabupaten Toraja Utara', '2026-09-03', '2026-09-08', 'Abdillah', 'Dikembalikan', 'Materi muatan perubahan tidak memiliki urgensi yang jelas mengingat pengaturan terkait objek pajak, tarif pajak, dan dasar pengenaan pajak mineral bukan logam dan batuan sudah diatur jelas dalam Peraturan Daerah dan peraturan Bupati Toraja Utara yang mengatur tentang pajak daerah.', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kota Palopo tentang Perubahan atas Peraturan Daerah Kota Palopo Nomor 5 Tahun 2021 tentang Perlindungan Lahan Pertanian Pangan Berkelanjutan', '-', 'Kota Palopo', '2026-09-05', '2026-09-09', 'Pramita', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kota Palopo tentang Perubahan atas Peraturan Daerah Kota Palopo Nomor 1 Tahun 2014 tentang Pengelolaan Sampah di Kota Palopo', '-', 'Kota Palopo', '2026-09-05', '2026-09-09', 'Fachruddin', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kota Palopo tentang Pengelolaan Barang Milik Daerah', '-', 'Kota Palopo', '2026-09-05', '2026-09-09', 'Pramita', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kota Palopo tentang Rencana Induk Pembangunan Kepariwisataan Daerah Tahun 2026–2040', '-', 'Kota Palopo', '2026-09-05', '2026-09-09', 'Syarif', 'Dikembalikan', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kota Palopo tentang Perubahan atas Peraturan Daerah Kota Palopo Nomor 1 Tahun 2024 tentang Pajak Daerah dan Retribusi Daerah', '-', 'Kota Palopo', '2026-09-05', '2026-09-09', 'Yuyun', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Tana Toraja tentang Pengakuan dan Perlindungan Masyarakat Hukum Adat', '-', 'Kabupaten Tana Toraja', '2026-09-02', '2026-09-09', 'Zulkifli', 'Dikembalikan', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Tana Toraja tentang Penanggulangan Tuberkulosis', '-', 'Kabupaten Tana Toraja', '2026-09-02', '2026-09-09', 'Rismayana', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Tana Toraja tentang Penyelenggaraan Penanggulangan Bencana', '-', 'Kabupaten Tana Toraja', '2026-09-02', '2026-09-09', 'Fatmawati', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Wajo tentang Perubahan Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2026', '-', 'Kabupaten Wajo', '2026-09-02', '2026-09-09', 'Agry', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Penjabaran Perubahan Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2026', '-', 'Kabupaten Wajo', '2026-09-02', '2026-09-09', 'Nurul', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperda Kabupaten Wajo tentang Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2027', '-', 'Kabupaten Wajo', '2026-09-05', '2026-09-09', 'Agry', 'Diterima', '', NULL);
INSERT INTO `harmonisasi` (`judul_rancangan`, `pemrakarsa`, `pemerintah_daerah`, `tanggal_surat_diterima`, `tanggal_rapat`, `pemegang_draf`, `status`, `alasan_pengembalian_draf`, `id_pengguna`) VALUES ('Ranperkada Kabupaten Wajo tentang Penjabaran Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2027', '-', 'Kabupaten Wajo', '2026-09-05', '2026-09-09', 'Nurul', 'Diterima', '', NULL);
