SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `Pegawai` (
  `NAMA` varchar(250) DEFAULT NULL,
  `NIP` char(18) NOT NULL,
  `PANGKAT_GOL_RUANG` varchar(100) DEFAULT NULL,
  `JABATAN` varchar(100) DEFAULT NULL,
  `UNIT_KERJA` varchar(200) DEFAULT NULL,
  `SATUAN_KERJA` varchar(200) DEFAULT NULL,
  `ATASAN_LANGSUNG` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `Pegawai`
--

INSERT INTO `Pegawai` (`NAMA`, `NIP`, `PANGKAT_GOL_RUANG`, `JABATAN`, `UNIT_KERJA`, `SATUAN_KERJA`, `ATASAN_LANGSUNG`) VALUES
('Dr. NICO AFINTA, S.I.K.,M.H.', '', ' ', 'Sekretaris Jenderal', 'Kementerian Hukum Republik Indonesia', 'Kementerian Hukum Republik Indonesia', ' '),
('Maemuna B, S.Sos., M.H.', '196902011992032001', 'Pembina Tk.I / IVb', 'Analis Hukum Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Syafruddin', '197008232025211009', 'Golongan V', 'Operator Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Puguh Wiyono, S.Sos., S.H., M.H.', '197103231995031001', 'Pembina Utama Muda / IVc', 'Penyuluh Hukum Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Serli Randabunga, S.H., M.H.', '197103301994032001', 'Pembina Tk.I / IVb', 'Penyuluh Hukum Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Norma, S.H.', '197105091990032001', 'Pembina / IVa', 'Perancang Peraturan Perundang-undangan Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Andi Basmal, S.Sos., S.H, M.H', '197202151992031002', 'Pembina Utama Muda / IVc', 'Kepala Kantor Wilayah Kementerian Hukum Sulawesi Selatan', 'Kantor Wilayah Sulawesi Selatan', 'Kantor Wilayah Sulawesi Selatan', 'Sekretaris Jenderal'),
('Basir, S.H., M.H.', '197211111993031001', 'Pembina Utama Muda / IVc', 'Analis SDM Aparatur Madya', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Kantor Wilayah Kementerian Hukum Sulawesi Selatan'),
('Asryani, S.H., M.H.', '197310112001122001', 'Pembina Tk.I / IVb', 'Perancang Peraturan Perundang-undangan Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Hasanuddin Andi, S.A.B, M.M.', '197311201997031001', 'Penata Tk.I / IIId', 'Analis Hukum Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Andi Rahmat, S.H.MM', '197401142003121001', 'Pembina / IVa', 'Analis SDM Aparatur Muda', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Saharuddin', '197406292025211020', 'Golongan V', 'Operator Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Andi Haris, S.H., M.H.', '197409012002121001', 'Pembina Tk.I / IVb', 'Kepala Bidang Pelayanan Kekayaan Intelektual', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Divisi Pelayanan Hukum'),
('Heny Widyawati, S.H., MH', '197601312001122001', 'Pembina Utama Muda / IVc', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Kantor Wilayah Kementerian Hukum Sulawesi Selatan'),
('Sitti Aminah, S.E.', '197602132005012001', 'Penata Tk.I / IIId', 'Pengolah Data dan Informasi', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Kekayaan Intelektual'),
('Mohammad Rusdiyanto Muin, S.H., M.H.', '197606132002121001', 'Pembina Tk.I / IVb', 'Analis Hukum Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Nuryuli Nurdin, S.H., M.H.', '197607302010122001', 'Penata / IIIc', 'Perancang Peraturan Perundang-undangan Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Baharuddin, S.H.,M.H.', '197703012010121001', 'Pembina Tk.I / IVb', 'Perancang Peraturan Perundang-undangan Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Mukhlis', '197704262025211044', 'Golongan V', 'Operator Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Syaiful , S.H., M.H.', '197801252009011008', 'Penata Tk.I / IIId', 'Penata Kelola Pemerintahan', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Administrasi Hukum Umum'),
('Nurlindah, S.H., M.H.', '197803282010122001', 'Penata / IIId', 'Perancang Peraturan Perundang-undangan Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Wawan Darmawan, S.H.', '197806222010121001', 'Penata Tk.I / IIId', 'Penelaah Teknis Kebijakan', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Adriana, S.E.', '197807192010122002', 'Penata Tk. I / IIId', 'Penata Kelola Pemerintahan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Ahmad M Mile, S.Kom. MM', '197901162009121003', 'Penata Tk. I / IIId', 'Pranata Hubungan Masyarakat Muda', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Dedy Ardianto Burhan, S.H.', '197903092006041001', 'Penata Tk.I / IIId', 'Analis Hukum Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Asis', '197903172025211032', 'Golongan I', 'Pengelola Umum Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Dr. Ramli, S.H., M.H.', '198001092000031001', 'Pembina / IVa', 'Kepala Bidang Pelayanan Administrasi Hukum Umum', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Divisi Pelayanan Hukum'),
('Erna, S.H., M.H.', '198002152006042001', 'Pembina / IVa', 'Penyuluh Hukum Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Wahyuddin Ardianto Machpudj, S.H., M.H.', '198003232003121001', 'Penata Tk.I / IIId', 'Penyuluh Hukum Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Santi Puspitasari, S.H.', '198003292003122001', 'Penata Tk.I / IIId', 'Pengelola Layanan Operasional', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Administrasi Hukum Umum'),
('Khomaini, S.H.,M.H', '198007052009121003', 'Pembina / IVa', 'Analis Anggaran Madya', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Malik Ibrahim, S.E.', '198011142010121002', 'Penata Tk.I / IIId', 'Penata Kelola Pemerintahan', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Administrasi Hukum Umum'),
('Demson Marihot, SE', '198011262009121002', 'Pembina Tk.I / IVb', 'Kepala Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Kantor Wilayah Kementerian Hukum Sulawesi Selatan'),
('Feny Feliana, S.H., M.Si.', '198102182005012001', 'Pembina / IVa', 'Analis Pengelolaan Keuangan APBN Muda', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Andi Wildania, S.H., M.H.', '198104102006042002', 'Penata Tk.I / IIId', 'Penata Kelola Pemerintahan', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Administrasi Hukum Umum'),
('Syamsinar Rasyid, S.K.M.', '198104202005012017', 'Pembina / IVa', 'Penata Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Amir Adib, A.Md.', '198108122009121003', 'Penata / IIIc', 'Penata Kelola Pemerintahan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Teguh Firmanto, S.H,. M.Si', '198109022006041001', 'Pembina Tk.I / IVb', 'Analis Kekayaan Intelektual Ahli Madya', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Divisi Pelayanan Hukum'),
('Awaluddin', '198201162025211037', 'Golongan V', 'Operator Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Firmanullah, S.H.', '198202082009121004', 'Penata / IIIc', 'Perancang Peraturan Perundang-undangan Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Sulastri Syarif, S.H.MM', '198211212005012001', ' Penata Muda Tk. I / IIIb', 'Analis SDM Aparatur Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Adly Azhari, S.Kom., M.H.', '198301052010121001', 'Penata Tk.I / IIId', 'Penyuluh Hukum Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Ikhsan Afrizal, S.H., M.Si.', '198303122008011009', 'Penata Tk.I / IIId', 'Analis Hukum Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Kurniati Hasan, S.H., M.H.', '198304052010122002', 'Penata / IIIc', 'Perancang Peraturan Perundang-undangan Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Nurlina, S.H., M.H', '198305122001122006', 'Pembina / IVa', 'Analis SDM Aparatur Madya', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Fitriani, S.H.,M.H', '198307172006042002', 'Penata Tk. I / IIId', 'Analis SDM Aparatur Muda', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('M Tasyriq R, S.P.', '198309202006041001', 'Penata / IIIc', 'Penata Kelola Pemerintahan', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Kekayaan Intelektual'),
('A. Rismayana, S.H.', '198310022010122003', 'Penata Tk.I / IIId', 'Perancang Peraturan Perundang-undangan Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Mayasari, S.H., M.H.', '198311012009012005', 'Pembina / IVa', 'Perancang Peraturan Perundang-undangan Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Syafar Syarif, S.H., M.H.', '198311112009121003', 'Penata / IIIc', 'Perancang Peraturan Perundang-undangan Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Andi Jayadi, S.H.', '198312132003121001', 'Penata Muda Tk. I/IIIb', 'Pengelola Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Nasruddin, S.H., M.H.', '198312202007031002', 'Penata Tk.I / IIId', 'Penyuluh Hukum Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Imran S', '198411182025211042', 'Golongan V', 'Operator Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Irma Wahyuni, S.H., M.H.', '198411252009122003', 'Pembina Tk.I / IVb', 'Perancang Peraturan Perundang-undangan Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Fajrin, S.E.', '198501022024211001', 'Golongan IX', 'Analis Kekayaan Intelektual Ahli Pertama', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Kekayaan Intelektual'),
('Jusriadi', '198503082025211050', 'Golongan V', 'Operator Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Nurhasnah, S.H', '198503152009012005', 'Penata / IIIc', 'Penata Kelola Pemerintahan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('A. Adryana Akbar, S.H.,M.H', '198505122009122006', 'Penata / IIIc', 'Perancang Peraturan Perundang-undangan Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Kiki Rezki Amalia, S.H.', '198505182003122001', 'Penata Tk.I / IIId', 'Pengelola Layanan Operasional', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Administrasi Hukum Umum'),
('Agry Caesar, S.E.', '198508162010121005', 'Penata Tk.I / IIId', 'Perancang Peraturan Perundang-undangan Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Marini Olivia Pandean, S.Kom., S.H.,M.H', '198510252014022003', 'Penata / IIIc', 'Penyuluh Hukum Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Arman, S.S.', '198601182009121005', 'Penata Tk. I / IIId', 'Penata Kelola Pemerintahan', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Administrasi Hukum Umum'),
('Andi Pramita Krisnayanti, S.H.,M.Kn.', '198603052009012002', 'Penata / IIIc', 'Perancang Peraturan Perundang-undangan Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Andi Muhammad Abdillah, S.H., M.H.', '198608122009121006', 'Pembina / IVa', 'Perancang Peraturan Perundang-undangan Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Arpan Rinaldy Tambila Barre, SH', '198608132012121001', 'Penata / IIIc', 'Perancang Peraturan Perundang-undangan Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Hans Patanduk, SH., MH', '198608212006041002', 'Penata Muda Tk. I/IIIb', 'Penata Kelola Pemerintahan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Dr. Muhamad Syarif As`ad, S.H.,M.H', '198612052010121001', 'Pembina / IVa', 'Perancang Peraturan Perundang-undangan Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Nurul Setiawan, S.H., M.H.', '198612162006041002', 'Penata Tk.I / IIId', 'Analis Kekayaan Intelektual Ahli Pertama', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Kekayaan Intelektual'),
('Alfira Nuril Badriana Ningrum Mujianto, S.E.MM', '198612202010122004', 'Penata Tk. I / IIId', 'Penelaah Teknis Kebijakan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Indah Yuliani, S.S.', '198701112012122001', 'Penata Tk. I / IIId', 'Penelaah Teknis Kebijakan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Meydi Zulqadri, S.H.,M.H', '198705132010121006', 'Pembina / IVa', 'Kepala Bagian Tata Usaha dan Umum', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Kantor Wilayah Kementerian Hukum Sulawesi Selatan'),
('Andi Nilda Affida Hasly, S.E., M.M.', '198706052010122005', 'Penata Tk. I / IIId', 'Penata Kelola Pemerintahan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Andi Nurfajri Riandini Arief, S.H.,M.H', '198709182010122005', 'Penata Tk.I / IIId', 'Analis Kekayaan Intelektual Ahli Muda', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Kekayaan Intelektual'),
('Irpandi, S.H. ', '198709252024211002', 'Golongan IX', 'Arsiparis Ahli Pertama ', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('A. Riri Asturi Tenri Banna, S.E., M.M.', '198710312010122003', 'Penata Tk. I / IIId', 'Penata Kelola Pemerintahan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('A. Fachruddin, S.H., M.H.', '198712042010121006', 'Penata / IIIc', 'Perancang Peraturan Perundang-undangan Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Fajrin T., S.E., M.M.', '198801302009121002', 'Penata Tk.I / IIId', 'Analis Anggaran Muda', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Zulkifli Annas, S.H.', '198803042012121001', 'Penata Muda Tk.I / IIIb', 'Perancang Peraturan Perundang-undangan Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Andi Fikri Fauzi Alimuddin, S.H.,M.H.', '198804262008011001', 'Penata Tk. I / IIId', 'Penyuluh Hukum Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Hikmah Amir, S.H., M.M.', '198807162014022004', 'Penata Muda Tk. I/IIIb', 'Penelaah Teknis Kebijakan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Zulhastanto, S.H.,M.H', '198807252008011001', 'Penata Muda Tk.I / IIIb', 'Analis Kekayaan Intelektual Ahli Pertama', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Kekayaan Intelektual'),
('Fatmawati Rahmat, S.H. M.H', '198808212010122005', 'Pembina / IVa', 'Perancang Peraturan Perundang-undangan Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Munawir Nur', '198905312025211061', 'Golongan IX', 'Penata Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Dr.. Muhammad Fadli, S.H., M.H.', '198907112012121001', 'Pembina / IVa', 'Perancang Peraturan Perundang-undangan Madya', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Andi Wahyu Iskandar Zainal, S.H, M.Kn', '198907232019011001', 'Penata Muda Tk.I / IIIb', 'Perancang Peraturan Perundang-undangan Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('RM. Danudirja Setia Budi, S.H.', '199004292012121002', 'Penata Tk.I / IIId', 'Perancang Peraturan Perundang-undangan Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('E v a, S.H.', '199007052009122001', 'Penata / IIIc', 'Penelaah Teknis Kebijakan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Fitriani. Hb, S.Kom.', '199007142022032001', 'Penata Muda/ IIIa', 'Pranata Komputer Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Faisal Noor Farezi, S.Kom.', '199008222020121001', 'Penata Muda Tk. I / IIIb', 'Pranata Komputer Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Muhammad Taufiq, S.T., M.M.', '199010102017121001', 'Penata Muda Tk. I/IIIb', 'Pranata Komputer Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Wahyu Arianto, SH', '199106252014021001', 'Penata Muda / IIIa', 'Pengolah Data dan Informasi', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Fadilah, S.H.', '199111262019012001', ' Penata Muda Tk. I / IIIb', 'Analis SDM Aparatur Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Amran Amri', '199201102017121005', 'Pengatur /Iic', 'Pengadministrasi Perkantoran', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Syaharuddin', '199204022025211035', 'Golongan V', 'Operator Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Andi Mekasari, S.H', '199205202020122001', 'Penata Muda Tk.I / IIIb', 'Analis Hukum Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Merlyanti Anwar, S.H.,M.H.', '199206052010122002', 'Penata / IIIc', 'Penyuluh Hukum Muda', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Yunus Lienardo, S.E.', '199208222020121001', 'Penata Muda Tk. I/IIIb', 'Penata Kelola Pemerintahan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Harson Sisang, S.H.', '199303272012121002', ' Penata Muda Tk. I / IIIb', 'Analis SDM Aparatur Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Frieska Aprianty, S.E.', '199304082022032004', 'Penata Muda/ IIIa', 'Analis Anggaran Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Muh. Irfan, S.sos', '199304162020121002', 'Penata Muda Tk. I/IIIb', 'Pranata Hubungan Masyarakat Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Adrianti, A.Md.Keb.', '199306042024212007', 'Golongan VII', 'Arsiparis Terampil ', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Administrasi Hukum Umum'),
('Yuniar Venta Tyas Puspita, S.Si.', '199306052025062002', 'Penata Muda/ IIIa', 'Analis Kekayaan Intelektual Ahli Pertama', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Kekayaan Intelektual'),
('Jarsyawan', '199309082012121002', 'Pengatur Tk. I/ IId', 'Penelaah Teknis Kebijakan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Ismail Shaleh Ruslin, S.A.P.M.Tr.A.P', '199404132012121002', 'Penata Muda Tk. I/IIIb', 'Penata Kelola Pemerintahan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('A Muhammad Nurfajrin Nasri, S.Kom., M.KP.', '199405102019011001', 'Penata Muda Tk. I/IIIb', 'Penelaah Teknis Kebijakan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Uswatun Hasanah', '199409052017122001', 'Pengatur /Iic', 'Pengadministrasi Perkantoran', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Andi Asrul Ashari', '199412132017121007', 'Pengatur / IIc', 'Pengadministrasi Perkantoran', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Andi Rina Arianti', '199412192017122001', 'Pengatur Muda Tk. I/II/b', 'Pengadministrasi Perkantoran', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Akbar Ainur Ramadhan, S.A.P', '199502042017121003', 'Penata Muda / IIIa', 'Penyuluh Hukum Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Erdi Sitorus, S.E', '199502072020121001', ' Penata Muda Tk. I / IIIb', 'Penata Kelola Pemerintahan', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Ahmad Rizal, S.H', '199504172019011001', ' Penata Muda Tk. I / IIIb', 'Analis SDM Aparatur Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Fajar Kartini', '199504212017122004', 'Pengatur / IIc', 'Pengadministrasi Perkantoran', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Administrasi Hukum Umum'),
('Amirah Balqis, S.H.', '199505082019012001', 'Penata Muda Tk.I / IIIb', 'Analis Kebijakan Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Al Amin Reynaldo Siyang Langi, S.H.', '199507092025061007', 'Penata Muda/ IIIa', 'Analis Hukum Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Indriati Putri Utami, S.Si.', '199509062025062006', 'Penata Muda/ IIIa', 'Analis Kekayaan Intelektual Ahli Pertama', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Kekayaan Intelektual'),
('Dolly Wattimena, S.H. MM', '199510072020122001', ' Penata Muda Tk. I / IIIb', 'Analis SDM Aparatur Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Siti Mahqfira Amanda Putri, S.H.', '199512282025062009', 'Penata Muda/ IIIa', 'Perancang Peraturan Perundang-undangan Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Ayuni Nurhidayah Bakri', '199602062017122001', 'Pengatur /Iic', 'Pengadministrasi Perkantoran', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Administrasi Hukum Umum'),
('Sulfahmi', '199602202025211048', 'Golongan V', 'Operator Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Fadil Tri Wahyudi, S.Kom.', '199604102025061010', 'Penata Muda/ IIIa', 'Pranata Komputer Ahli Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Nursaid', '199608122017121002', 'Pengatur /Iic', 'Pengadministrasi Perkantoran', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Administrasi Hukum Umum'),
('Nasri', '199609102025211050', 'Golongan V', 'Operator Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Mardiana Marwan, SH', '199612012020122001', 'Penata Muda Tk. I/IIIb', 'Analis Kekayaan Intelektual Ahli Pertama', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Kekayaan Intelektual'),
('A Muh Samman, S.H.', '199705212025061009', 'Penata Muda/ IIIa', 'Analis Hukum Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Syahrah Rugaya Hamsah, S.H.', '199705292019012001', 'Penata Muda Tk.I / IIIb', 'Perancang Peraturan Perundang-undangan Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Fatimah Dwi Safitri, S.H.', '199710032020122001', 'Penata Muda Tk.I / IIIb', 'Pengolah Data dan Informasi', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Kekayaan Intelektual'),
('Maharani Nur Pratiwi', '199804282017122003', 'Pengatur Muda Tk. I/IIb', 'Pengadministrasi Perkantoran', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('A. Adelya Lubis', '199806122017122001', 'Pengatur /Iic', 'Pengadministrasi Perkantoran', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Deffri Kun Indarta, S.Kom.', '199812012025061010', 'Penata Muda/ IIIa', 'Analis Sumber Daya Manusia Aparatur Ahli Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Nurqalbi B, S.S.', '199901242025062008', 'Penata Muda/ IIIa', 'Analis Kekayaan Intelektual Ahli Pertama', 'Divisi Pelayanan Hukum', 'Divisi Pelayanan Hukum', 'Kepala Bidang Pelayanan Kekayaan Intelektual'),
('Devita Ayu Maharani, S.H.', '199906082022032001', 'Penata Muda / IIIa', 'Penyuluh Hukum Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Hamsyah Burhan', '199907252017121002', 'Pengatur /Iic', 'Pengadministrasi Perkantoran', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Salma Rahmi Pratiwi, S.H.', '199907302025062014', 'Penata Muda/ IIIa', 'Perancang Peraturan Perundang-undangan Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Bahrianto', '199909012025211039', 'Golongan V', 'Operator Layanan Operasional', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Rezky Wahyuni Anni Saputri Agm, S.H.', '200006222025062014', 'Penata Muda/ IIIa', 'Perancang Peraturan Perundang-undangan Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Andi Dio Batary Asrudi, S.H.', '200007292025062022', 'Penata Muda/ IIIa', 'Perancang Peraturan Perundang-undangan Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Randi Mursalim, S.Kom.', '200008042025061009', 'Penata Muda/ IIIa', 'Pranata Komputer Ahli Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Ayu Risma Dwiningsih, A.Md.E', '200009082022032002', 'Pengatur / IIc', 'Pranata Keuangan Anggaran Pendapatan dan Belanja Negara Terampil', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Andi Rizka Auliah, S.I.P.', '200011072025062016', 'Penata Muda/ IIIa', 'Analis Kebijakan Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Fahreza Aditya Pratama, S.I.P.', '200101132025061011', 'Penata Muda/ IIIa', 'Analis Kebijakan Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Irfani Febriyanti Fahmil, S.I.P.', '200102132025062020', 'Penata Muda/ IIIa', 'Analis Kebijakan Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Nur Aflihyana Bugi, S.H.', '200109202025062015', 'Penata Muda/ IIIa', 'Analis Hukum Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum'),
('Andi Syahrizal Al Azahra, S.Kom.', '200110022025061003', 'Penata Muda/ IIIa', 'Pranata Komputer Ahli Pertama', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Siska Wulandari', '199110112017122001', 'Penata Muda / IIIa', 'Pengadministrasi Perkantoran', 'Bagian TU dan UMUM', 'Bagian TU dan UMUM', 'Kepala Bagian Tata Usaha dan Umum'),
('Nurul Rachmadani, S.H.', '200111182025062010', 'Penata Muda/ IIIa', 'Perancang Peraturan Perundang-undangan Ahli Pertama', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Divisi Peraturan Perundang-undangan dan Pembinaan Hukum', 'Kepala Divisi Peraturan Perundang-undangan dan Pembinaan Hukum');

-- --------------------------------------------------------

--
-- Struktur dari tabel `skp_akhir_pegawai`
--


COMMIT;
